### ISSUE TITLE
How do I use it offline

### ISSUE THREAD

**Issue by Muppet1** [thomasoa/hand-evaluator-page#4]
Hi I love binky and drive my friends mad with it in general.

How do I make it work offline.  First guess is press download and see what happens will post more if I work it out.  Other useless people will also need to be told simple things like this.

Ok that was pretty easy I'll check later it works when I'm offline but looks like it will.

Now I don't have to do Danny Klein calculations in my head when I'm offline.

Oh there is no binky :-(.  Hope it will reappear sometime.  Hmm not sure what to use in the mean time maybe 5ths for Nt and bumrap for suits.

Also to use in a practical way I assume I actually have to change the eval as I discover how big the fit is because it normally just bases its values on the best suit fit with a random hand opposite.
So lets say I find we actually have a 9 card fit I'm guessing I need to be adding something.  I'll reread the articles not read them in a while.
Ok reread the reevaluation article time to play some hands.

Thanks

**Comment by thomasoa** [comment]
Yeah, I haven't gotten around to adding Binky back in yet. It's coming. Was working on other things.

To use it offline, you have to be on a computer, not a mobile device. In the computer, visit the evaluator page, then click "Save as..." or "Save Page as...", usually found in the "File" menu, depending on the browser. 

The file that you save will be something you can open on your computer without being on the internet. It won't reflect any new features added since you downloaded it.

**Comment by thomasoa** [comment]
Added code to implement Binky suit and notrump.
